// <auto-generated />
using System;
using Contratacao.Web.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contratacao.Web.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(ContratacaoDbContext))]
    [Migration("20261006124422_OrdemServicoDoContrato")]
    partial class OrdemServicoDoContrato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contratacao.Web.Domain.Anexos.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DemandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Etapa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EtapaId");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("Tamanho")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UsuarioUploadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DemandaId")
                        .HasDatabaseName("IX_Anexo_Demanda");

                    b.HasIndex("Etapa");

                    b.HasIndex("UsuarioUploadId");

                    b.ToTable("Anexo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Anexo_Categoria", "Categoria IN ('Geral', 'DeAcordoVP2')");
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Auditoria.HistoricoAlteracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DemandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NovoValor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfilUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("DemandaId", "DataHora")
                        .HasDatabaseName("IX_HistAlt_Demanda");

                    b.ToTable("HistoricoAlteracao", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Auditoria.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NovoValor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfilUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidade", "EntidadeId", "DataHora")
                        .HasDatabaseName("IX_Log_Entidade");

                    b.ToTable("LogAuditoria", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Catalogos.GerenteExecutivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("GerenteExecutivo", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Catalogos.ItemEquipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_ItemEquipamento_Nome");

                    b.ToTable("ItemEquipamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000001"),
                            Ativo = true,
                            Nome = "Notebook",
                            Valor = 444.35m
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000002"),
                            Ativo = true,
                            Nome = "Segunda tela",
                            Valor = 53.93m
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000003"),
                            Ativo = true,
                            Nome = "Celular",
                            Valor = 118.64m
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Catalogos.ModeloTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_ModeloTrabalho_Nome");

                    b.ToTable("ModeloTrabalho", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000001"),
                            Nome = "Presencial"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000002"),
                            Nome = "Híbrido"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000003"),
                            Nome = "Remoto"
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Catalogos.Rac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Rac_Codigo");

                    b.ToTable("Rac", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Catalogos.TipoDemanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_TipoDemanda_Nome");

                    b.ToTable("TipoDemanda", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000001"),
                            Ativo = true,
                            Nome = "Nova contratação"
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Contratos.Contratada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .HasColumnName("CNPJ")
                        .IsFixedLength();

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UQ_Contratada_CNPJ")
                        .HasFilter("[CNPJ] IS NOT NULL");

                    b.ToTable("Contratada", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000001"),
                            Ativo = true,
                            RazaoSocial = "SESI"
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Contratos.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("ContratadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ContratadaId");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("UQ_Contrato_Numero");

                    b.ToTable("Contrato", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contrato_Numero", "Numero LIKE '59%' AND Numero NOT LIKE '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000001"),
                            Ativo = true,
                            ContratadaId = new Guid("00000008-0000-0000-0000-000000000001"),
                            Numero = "5900125082"
                        },
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000002"),
                            Ativo = true,
                            ContratadaId = new Guid("00000008-0000-0000-0000-000000000001"),
                            Numero = "5900118506"
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Contratos.Corredor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("Nome", "RegiaoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Corredor_NomeRegiao");

                    b.ToTable("Corredor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000001"),
                            Ativo = true,
                            ContratoId = new Guid("00000009-0000-0000-0000-000000000001"),
                            Nome = "Norte",
                            RegiaoId = new Guid("0000000a-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000002"),
                            Ativo = true,
                            ContratoId = new Guid("00000009-0000-0000-0000-000000000001"),
                            Nome = "Pelotização",
                            RegiaoId = new Guid("0000000a-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000003"),
                            Ativo = true,
                            ContratoId = new Guid("00000009-0000-0000-0000-000000000001"),
                            Nome = "C. Integrado",
                            RegiaoId = new Guid("0000000a-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000004"),
                            Ativo = true,
                            ContratoId = new Guid("00000009-0000-0000-0000-000000000002"),
                            Nome = "Sudeste",
                            RegiaoId = new Guid("0000000a-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000005"),
                            Ativo = true,
                            ContratoId = new Guid("00000009-0000-0000-0000-000000000002"),
                            Nome = "Sul",
                            RegiaoId = new Guid("0000000a-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000006"),
                            Ativo = true,
                            ContratoId = new Guid("00000009-0000-0000-0000-000000000002"),
                            Nome = "Pelotização",
                            RegiaoId = new Guid("0000000a-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000007"),
                            Ativo = true,
                            ContratoId = new Guid("00000009-0000-0000-0000-000000000002"),
                            Nome = "C. Integrado",
                            RegiaoId = new Guid("0000000a-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Contratos.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("UQ_OrdemServico_ContratoNumero");

                    b.ToTable("OrdemServico", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.Demanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaSolicitante")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CategoriaCnh")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<bool>("Celular")
                        .HasColumnType("bit");

                    b.Property<string>("ColetorCusto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ContratadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorredorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CustoTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoAtividades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Etapa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EtapaAtualId");

                    b.Property<bool>("ExigeCnh")
                        .HasColumnType("bit");

                    b.Property<string>("FiscalEfetivoEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FiscalEfetivoNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Formacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("GerenteExecutivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemQqpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocalidadeVaga")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ModeloTrabalhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Notebook")
                        .HasColumnType("bit");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short?>("PeriodoTemporarioMeses")
                        .HasColumnType("smallint");

                    b.Property<decimal>("PisoSalarialQqp")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PrecoUnitarioQqp")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<short>("QuantidadeSolicitada")
                        .HasColumnType("smallint");

                    b.Property<string>("ResponsavelEfetivoEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("ResponsavelEfetivoNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ResponsavelSesiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("SegundaTela")
                        .HasColumnType("bit");

                    b.Property<Guid>("Status")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatusAtualId");

                    b.Property<bool>("Temporaria")
                        .HasColumnType("bit");

                    b.Property<Guid>("TipoDemandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioSolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorEquipamentosPorPessoa")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContratadaId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("CorredorId");

                    b.HasIndex("GerenteExecutivoId");

                    b.HasIndex("GestorId")
                        .HasDatabaseName("IX_Demanda_Gestor");

                    b.HasIndex("ItemQqpId");

                    b.HasIndex("ModeloTrabalhoId");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("UQ_Demanda_Numero");

                    b.HasIndex("OrdemServicoId");

                    b.HasIndex("ResponsavelSesiId")
                        .HasDatabaseName("IX_Demanda_ResponsavelSesi");

                    b.HasIndex("Status");

                    b.HasIndex("TipoDemandaId");

                    b.HasIndex("UsuarioSolicitanteId")
                        .HasDatabaseName("IX_Demanda_Solicitante");

                    b.HasIndex("Etapa", "Status")
                        .HasDatabaseName("IX_Demanda_EtapaStatus");

                    b.ToTable("Demanda", null, t =>
                        {
                            t.HasCheckConstraint("CK_Demanda_CategoriaCnh", "CategoriaCnh IN ('A','B','C','D','E','AB','AC','AD','AE')");

                            t.HasCheckConstraint("CK_Demanda_Cnh", "ExigeCnh = 0 OR CategoriaCnh IS NOT NULL");

                            t.HasCheckConstraint("CK_Demanda_Finalizacao", "DataFinalizacao IS NULL OR DataFinalizacao >= DataCriacao");

                            t.HasCheckConstraint("CK_Demanda_Quantidade", "QuantidadeSolicitada > 0");

                            t.HasCheckConstraint("CK_Demanda_Sla", "DataLimiteSLA IS NULL OR DataLimiteSLA >= CAST(DataInicioSLA AS date)");

                            t.HasCheckConstraint("CK_Demanda_Temporaria", "Temporaria = 0 OR PeriodoTemporarioMeses > 0");
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.DemandaRac", b =>
                {
                    b.Property<Guid>("DemandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RacId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DemandaId", "RacId")
                        .HasName("PK_DemandaRac");

                    b.HasIndex("RacId");

                    b.ToTable("DemandaRac", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.EtapaDemanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DemandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Etapa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EtapaId");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("Status")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatusId");

                    b.Property<Guid?>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DemandaId")
                        .HasDatabaseName("IX_EtapaDemanda_Demanda");

                    b.HasIndex("Etapa");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("EtapaDemanda", null, t =>
                        {
                            t.HasCheckConstraint("CK_EtapaDemanda_Datas", "DataConclusao IS NULL OR DataConclusao >= DataInicio");
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.HistoricoDemanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DemandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<Guid?>("EtapaAnterior")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EtapaAnteriorId");

                    b.Property<Guid>("EtapaNova")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EtapaNovaId");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Acao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PerfilUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("StatusAnterior")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatusAnteriorId");

                    b.Property<Guid>("StatusNovo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatusNovoId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EtapaAnterior");

                    b.HasIndex("EtapaNova");

                    b.HasIndex("StatusAnterior");

                    b.HasIndex("StatusNovo");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("DemandaId", "DataHora")
                        .HasDatabaseName("IX_HistDemanda_Demanda");

                    b.ToTable("HistoricoDemanda", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.SolicitacaoCorrecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DemandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("SolicitadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DemandaId")
                        .HasDatabaseName("IX_Correcao_Demanda");

                    b.HasIndex("SolicitadoPorId");

                    b.ToTable("SolicitacaoCorrecao", null, t =>
                        {
                            t.HasCheckConstraint("CK_Correcao_Origem", "Origem IN ('Gestor', 'SESI')");

                            t.HasCheckConstraint("CK_Correcao_Tipo", "Tipo IN ('Solicitante', 'Contratual')");

                            t.HasCheckConstraint("CK_Correcao_TipoOrigem", "(Origem = 'SESI' AND Tipo IS NOT NULL) OR (Origem = 'Gestor' AND Tipo IS NULL)");
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.Vaga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DemandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkExterno")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DemandaId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Vaga_Demanda")
                        .HasFilter("[DemandaId] IS NOT NULL");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("Vaga", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Parametros.ParametroSistema", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("AlteradoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Chave");

                    b.HasIndex("AlteradoPorId");

                    b.ToTable("ParametroSistema", (string)null);

                    b.HasData(
                        new
                        {
                            Chave = "PrazoSlaDias",
                            DataAlteracao = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "45"
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Parametros.SequenciaNumeroDemanda", b =>
                {
                    b.Property<short>("Ano")
                        .HasColumnType("smallint");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("int");

                    b.HasKey("Ano");

                    b.ToTable("SequenciaNumeroDemanda", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Qqp.ItemQqp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CargaHorariaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassificacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<Guid>("FuncaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NivelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PisoSalarial")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CargaHorariaId");

                    b.HasIndex("ClassificacaoId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_ItemQqp_Codigo");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("NivelId");

                    b.HasIndex("RegiaoId", "FuncaoId", "ClassificacaoId", "NivelId", "CargaHorariaId")
                        .HasDatabaseName("IX_ItemQqp_Busca");

                    b.ToTable("ItemQqp", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Qqp.QqpCargaHoraria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("HorasSemanais")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("HorasSemanais")
                        .IsUnique()
                        .HasDatabaseName("UQ_QqpCargaHoraria");

                    b.ToTable("QqpCargaHoraria", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Qqp.QqpClassificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_QqpClassificacao_Nome");

                    b.ToTable("QqpClassificacao", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Qqp.QqpFuncao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_QqpFuncao_Nome");

                    b.ToTable("QqpFuncao", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Qqp.QqpNivel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_QqpNivel_Nome");

                    b.ToTable("QqpNivel", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Qqp.QqpRegiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_QqpRegiao_Nome");

                    b.ToTable("QqpRegiao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0000000a-0000-0000-0000-000000000001"),
                            Nome = "QQP NORTE"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0000-0000-0000-000000000002"),
                            Nome = "QQP SUDESTE"
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Usuarios.GestorContrato", b =>
                {
                    b.Property<Guid>("GestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GestorId", "ContratoId")
                        .HasName("PK_GestorContrato");

                    b.HasIndex("ContratoId");

                    b.ToTable("GestorContrato", (string)null);
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CriadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeveTrocarSenha")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<Guid?>("GestorResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("Perfil")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PerfilId");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_Email");

                    b.HasIndex("GestorResponsavelId");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_Login");

                    b.HasIndex("Perfil");

                    b.ToTable("Usuario", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_Email_Dominio", "Email LIKE '%@ucl.br'");
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaEtapa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_Etapa_Nome");

                    b.HasIndex("Ordem")
                        .IsUnique()
                        .HasDatabaseName("UQ_Etapa_Ordem");

                    b.ToTable("Etapa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000001"),
                            Ativa = true,
                            Nome = "Solicitação",
                            Ordem = (short)1
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000002"),
                            Ativa = true,
                            Nome = "Validação do Gestor",
                            Ordem = (short)2
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000003"),
                            Ativa = true,
                            Nome = "Validação SESI",
                            Ordem = (short)3
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000004"),
                            Ativa = true,
                            Nome = "Recrutamento",
                            Ordem = (short)4
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000005"),
                            Ativa = true,
                            Nome = "Entrevistas",
                            Ordem = (short)5
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000006"),
                            Ativa = true,
                            Nome = "Exames Médicos",
                            Ordem = (short)6
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000007"),
                            Ativa = true,
                            Nome = "Contratação",
                            Ordem = (short)7
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_Perfil_Nome");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Descricao = "Criador/Admin: gerencia Gestores, parâmetros e auditoria",
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000002"),
                            Descricao = "Gestor do Contrato: valida, devolve e cancela demandas dos seus contratos",
                            Nome = "Gestor"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000003"),
                            Descricao = "Usuário Solicitante: cria, envia e corrige demandas",
                            Nome = "Solicitante"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000004"),
                            Descricao = "Funcionário SESI: conduz o processo das demandas do seu contrato",
                            Nome = "FuncionarioSesi"
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_Status_Nome");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000001"),
                            Ativo = true,
                            Nome = "Em análise"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000002"),
                            Ativo = true,
                            Nome = "Aguardando correção"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000003"),
                            Ativo = true,
                            Nome = "Aguardando responsável"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000004"),
                            Ativo = true,
                            Nome = "Em andamento"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000005"),
                            Ativo = true,
                            Nome = "Concluído"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000006"),
                            Ativo = true,
                            Nome = "Cancelado"
                        });
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Anexos.Anexo", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Demandas.Demanda", null)
                        .WithMany()
                        .HasForeignKey("DemandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Anexo_Demanda");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaEtapa", null)
                        .WithMany()
                        .HasForeignKey("Etapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Anexo_Etapa");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioUploadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Anexo_Usuario");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Auditoria.HistoricoAlteracao", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Demandas.Demanda", null)
                        .WithMany("Alteracoes")
                        .HasForeignKey("DemandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HistAlt_Demanda");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HistAlt_Usuario");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Auditoria.LogAuditoria", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Log_Usuario");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Contratos.Contrato", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Contratos.Contratada", null)
                        .WithMany()
                        .HasForeignKey("ContratadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contrato_Contratada");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Contratos.Corredor", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Contratos.Contrato", null)
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Corredor_Contrato");

                    b.HasOne("Contratacao.Web.Domain.Qqp.QqpRegiao", null)
                        .WithMany()
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Corredor_Regiao");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Contratos.OrdemServico", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Contratos.Contrato", null)
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrdemServico_Contrato");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.Demanda", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Contratos.Contratada", null)
                        .WithMany()
                        .HasForeignKey("ContratadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_Contratada");

                    b.HasOne("Contratacao.Web.Domain.Contratos.Contrato", null)
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_Contrato");

                    b.HasOne("Contratacao.Web.Domain.Contratos.Corredor", null)
                        .WithMany()
                        .HasForeignKey("CorredorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_Corredor");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaEtapa", null)
                        .WithMany()
                        .HasForeignKey("Etapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_Etapa");

                    b.HasOne("Contratacao.Web.Domain.Catalogos.GerenteExecutivo", null)
                        .WithMany()
                        .HasForeignKey("GerenteExecutivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_GerenteExecutivo");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Demanda_Gestor");

                    b.HasOne("Contratacao.Web.Domain.Qqp.ItemQqp", null)
                        .WithMany()
                        .HasForeignKey("ItemQqpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_ItemQqp");

                    b.HasOne("Contratacao.Web.Domain.Catalogos.ModeloTrabalho", null)
                        .WithMany()
                        .HasForeignKey("ModeloTrabalhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_ModeloTrabalho");

                    b.HasOne("Contratacao.Web.Domain.Contratos.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_OrdemServico");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelSesiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Demanda_ResponsavelSesi");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaStatus", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_Status");

                    b.HasOne("Contratacao.Web.Domain.Catalogos.TipoDemanda", null)
                        .WithMany()
                        .HasForeignKey("TipoDemandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_TipoDemanda");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Demanda_Solicitante");

                    b.OwnsOne("Contratacao.Web.Domain.Prazos.Sla", "Sla", b1 =>
                        {
                            b1.Property<Guid>("DemandaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataLimite")
                                .HasColumnType("date")
                                .HasColumnName("DataLimiteSLA");

                            b1.Property<DateTime>("InicioUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataInicioSLA");

                            b1.Property<short>("PrazoDias")
                                .HasColumnType("smallint")
                                .HasColumnName("PrazoDiasSla");

                            b1.HasKey("DemandaId");

                            b1.HasIndex("DataLimite")
                                .HasDatabaseName("IX_Demanda_LimiteSla");

                            b1.ToTable("Demanda");

                            b1.WithOwner()
                                .HasForeignKey("DemandaId");
                        });

                    b.Navigation("Sla");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.DemandaRac", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Demandas.Demanda", null)
                        .WithMany("Racs")
                        .HasForeignKey("DemandaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_DemandaRac_Demanda");

                    b.HasOne("Contratacao.Web.Domain.Catalogos.Rac", null)
                        .WithMany()
                        .HasForeignKey("RacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DemandaRac_Rac");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.EtapaDemanda", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Demandas.Demanda", null)
                        .WithMany("Etapas")
                        .HasForeignKey("DemandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EtapaDemanda_Demanda");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaEtapa", null)
                        .WithMany()
                        .HasForeignKey("Etapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EtapaDemanda_Etapa");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaStatus", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EtapaDemanda_Status");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EtapaDemanda_Usuario");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.HistoricoDemanda", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Demandas.Demanda", null)
                        .WithMany("Historico")
                        .HasForeignKey("DemandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HistDemanda_Demanda");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaEtapa", null)
                        .WithMany()
                        .HasForeignKey("EtapaAnterior")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HistDemanda_EtapaAnt");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaEtapa", null)
                        .WithMany()
                        .HasForeignKey("EtapaNova")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HistDemanda_EtapaNova");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusAnterior")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HistDemanda_StatusAnt");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusNovo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HistDemanda_StatusNovo");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HistDemanda_Usuario");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.SolicitacaoCorrecao", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Demandas.Demanda", null)
                        .WithMany("Correcoes")
                        .HasForeignKey("DemandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Correcao_Demanda");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("SolicitadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Correcao_Usuario");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.Vaga", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Demandas.Demanda", null)
                        .WithOne("Vaga")
                        .HasForeignKey("Contratacao.Web.Domain.Demandas.Vaga", "DemandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Vaga_Demanda");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Vaga_Usuario");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Parametros.ParametroSistema", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Parametro_Usuario");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Qqp.ItemQqp", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Qqp.QqpCargaHoraria", null)
                        .WithMany()
                        .HasForeignKey("CargaHorariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ItemQqp_Carga");

                    b.HasOne("Contratacao.Web.Domain.Qqp.QqpClassificacao", null)
                        .WithMany()
                        .HasForeignKey("ClassificacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ItemQqp_Classificacao");

                    b.HasOne("Contratacao.Web.Domain.Qqp.QqpFuncao", null)
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ItemQqp_Funcao");

                    b.HasOne("Contratacao.Web.Domain.Qqp.QqpNivel", null)
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ItemQqp_Nivel");

                    b.HasOne("Contratacao.Web.Domain.Qqp.QqpRegiao", null)
                        .WithMany()
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ItemQqp_Regiao");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Usuarios.GestorContrato", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Contratos.Contrato", null)
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GestorContrato_Contrato");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GestorContrato_Gestor");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Contratacao.Web.Domain.Contratos.Contrato", null)
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Usuario_Contrato");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Usuario_CriadoPor");

                    b.HasOne("Contratacao.Web.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("GestorResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Usuario_Gestor");

                    b.HasOne("Contratacao.Web.Infrastructure.Persistencia.Catalogos.LinhaPerfil", null)
                        .WithMany()
                        .HasForeignKey("Perfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Perfil");
                });

            modelBuilder.Entity("Contratacao.Web.Domain.Demandas.Demanda", b =>
                {
                    b.Navigation("Alteracoes");

                    b.Navigation("Correcoes");

                    b.Navigation("Etapas");

                    b.Navigation("Historico");

                    b.Navigation("Racs");

                    b.Navigation("Vaga");
                });
#pragma warning restore 612, 618
        }
    }
}
